### ISSUE TITLE
--wait argument is ignored

### ISSUE THREAD

**Issue by franciscovilchezv** [forestagostinelli/Deep_Reinforcement_Learning_and_Search_Class#1]
Hi @forestagostinelli 

I think there is a small issue in farm_visualizer.py line 135.

It says: `time.sleep(0.0)`
But I think it should say: `time.sleep(self.wait)`

I wanted to mention it just to save a few minutes to my classmates that were wondering why the —wait argument was being ignored.

**Comment by forestagostinelli** [comment]
Yes, thank you, @franciscovilchezv

**Comment by forestagostinelli** [comment]
Fixed in update
